[package]
name = "orion-encrypt"
version = "0.1.0"
authors = ["blake"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orion = "0.15.2"
base64 = "0.12.3"
paw = "1.0.0"
